### ISSUE TITLE
Contribute the work to chirp upstream?

### ISSUE THREAD

**Issue by FlyGoat** [sfc9982/SenHaiX-8600-FreqWrite#1]
I was trying to implement CHIRP support for SHX8800 [1], [2]. It was almost done but pending upstreaming due to I lost access to my RIG.

I just had a galance on this implementation and it seems like the protocol is almost the same depite some difference on EEPROM bit fields.

Would you mind to contribute this work to upstream together with SHX8800 one?

Thanks
[1]: https://chirp.danplanet.com/issues/7997
[2]: https://github.com/FlyGoat/chirp-shx8800

de 73 GM3HSO/BH5HSO

**Comment by sfc9982** [comment]
可以说中文

**Comment by sfc9982** [comment]
这个功能不比官方写频软件多，写着玩的

**Comment by FlyGoat** [comment]
ok.....
我是觉得CHIRP没人推挺可惜的...

**Comment by sfc9982** [comment]
可以说中文？

**Comment by bushnerd** [comment]
https://chirp.danplanet.com/issues/10555

这个里面提到会去适配8600。
CHIRP在国内怎么用的人这么少，是有点可惜。国内关于中继的信息发布都没有一个集中的平台，真可惜。
